task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 1 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/datasets/Windturbine/multi-topography-dataset-for-wind-turbine-detection-DatasetNinja-expanded/ds/images/train
    ann_file: D:/datasets/Windturbine/multi-topography-dataset-for-wind-turbine-detection-DatasetNinja-expanded/ds/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/datasets/Windturbine/multi-topography-dataset-for-wind-turbine-detection-DatasetNinja-expanded/ds/images/val
    ann_file: D:/datasets/Windturbine/multi-topography-dataset-for-wind-turbine-detection-DatasetNinja-expanded/ds/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction